# -*- coding: utf-8 -*-
"""Homework 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sDbc7xjsD6V52jlGJP36zfqE3a6uobNi
"""

import json,requests

repeat="yes"
print("Hello, welcome to the predictive text Haiku generator!")
while repeat.lower()=="yes":
  try:
    words0=[]
    words1=[]
    words2=[]
    words3=[]
    words4=[]
    words5=[]
    words6=[]
    search = input("What would you like to see a Haiku about? ")
    base_url1 = "https://api.datamuse.com/words?md=s&rel_trg="
    full_url1 = base_url1 + search
    print(full_url1)
    response1 = requests.get(full_url1)
    if response1:
        data1 = json.loads(response1.text)    
        for line in data1:
          syllables1=line["numSyllables"]
          word = line["word"]
          if(syllables1==3):
            words0.append(word)         
        search1=words0[0]
        print("Word 0:",search1)
    #**** Word 1 ****    
        base_url2 = "https://api.datamuse.com/words?md=s&lc="
        full_url2 = base_url2 + search1
        response2 = requests.get(full_url2)
        print(full_url2)
        if response2:
          data2 = json.loads(response2.text)  
          for line in data2:
            syllables2=line["numSyllables"]
            word1 = line["word"]
            if(syllables2==2):
              words1.append(word1)
          search2=words1[0]
          print("Word 1:",search2)
    #**** Word 2 ****  
        full_url3 = base_url2 + search2
        response3 = requests.get(full_url3)
        print(full_url3)
        if response3:
          data3 = json.loads(response3.text)  
          for line in data3:
            syllables3=line["numSyllables"]
            word2 = line["word"]
            if(syllables3==3):
              words2.append(word2)
          search3=words2[0]
          print("Word 2:",search3)
    #**** Word 3 ****  

        full_url4 = base_url2 + search3
        response4 = requests.get(full_url4)
        print(full_url4)
        if response4:
          data4 = json.loads(response4.text)  
          for line in data4:
            syllables4=line["numSyllables"]
            word3 = line["word"]
            if(syllables4==2):
              words3.append(word3)
          search4=words3[0]
          print("Word 3:",search4)
      #**** Word 4 ****  

        full_url5 = full_url4 + "&rel_rhy="
        full_url6 = full_url5 + search2
        print(full_url6)
        response5 = requests.get(full_url6)
        if response5:
          data5 = json.loads(response5.text)  
          for line in data5:
            syllables5=line["numSyllables"]
            word5 = line["word"]
            if(syllables5==2):
              words4.append(word5)
          search5=words4[0]
          print("Word 4:",search5)
      #**** Word 5 ****

        full_url7 = base_url2 + search5
        print(full_url7)
        response6 = requests.get(full_url7)
        if response6:
          data6 = json.loads(response6.text)  
          for line in data6:
            syllables6=line["numSyllables"]
            word6 = line["word"]
            if(syllables6==3):
              words5.append(word6)
          search4=words5[0]
          print("Word 5:",search4)

      #**** Word 6 ****  
        full_url8 = base_url2 + search4 + "&rel_rhy="
        full_url9 = full_url8 + search2
        print(full_url9,"**")
        response7 = requests.get(full_url9)
        if response7:
          data7 = json.loads(response7.text)  
          for line in data7:
            syllables7=line["numSyllables"]
            word7 = line["word"]
            if(syllables7==2 and word7!=search5):
              words6.append(word7)
          search7=words6[0]
          print("Word 6:",search7)
  except:

    print("Sorry, a valid Haiku could not be generated.")

print("\n\n\nFinal Output:")    
print(words0[0],"",words1[0])
print(words2[0],"",words3[0],"",words4[0])
print(words5[0],"",words6[0])
repeat = input("Would you like to see another Haiku (yes/no)?")